services:
  - type: web
    name: kachra-ai
    env: python
    plan: free
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 200 --workers 1 --threads 2
    envVars:
      - key: HF_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /
